packages:
  - 'client/*'
  - 'core/*'
  - 'core/config-editor/src-node-sidecar'
  - 'core/relay-server/client'
  - 'examples/full-local/game/*'
  - 'examples/full-local/integration'
  - 'examples/full-local/services/*'
  - 'examples/full-local/tests/webrtc'
  - 'github-pages'
  - 'plugins/download/archive/*'
  - 'plugins/download/compression/*'
  - 'plugins/download/protocol'
  - 'plugins/download/protocol/*'
  - 'plugins/download/shared'
  - 'plugins/piece-selection-sort/*'
  - 'plugins/untrusted/config/*'
  - 'plugins/untrusted/script/*'
