packages:
  - 'client/*'
  - 'core/*'
  - 'core/match-agent/client'
  - 'core/config-editor/*'
  - 'core/config-editor-cli'
  - 'core/relay-server/*'
  - 'examples/full-local/game/*'
  - 'examples/full-local/integration'
  - 'examples/full-local/services/*'
  - 'examples/full-local/tests/pwa'
  - 'examples/full-local/tests/webrtc'
  - 'examples/mugen/integration'
  - 'examples/mugen/playwright'
  - 'examples/services/*'
  - 'examples/services/coordinators/*'
  - 'examples/services/match-makers/*'
  - 'examples/services/match-makers/titled-room/client'
  - 'examples/services/download-provider/*'
  - 'github-pages'
  - 'plugins/download/archive/*'
  - 'plugins/download/compression/*'
  - 'plugins/download/protocol'
  - 'plugins/download/protocol/*'
  - 'plugins/download/shared'
  - 'plugins/piece-selection-sort/*'
  - 'plugins/game-runner/*'
  - 'plugins/game-runner/shared/*'
  - 'examples/multi-game-room/services/*'
  - 'plugins/untrusted/config/*'
  - 'plugins/untrusted/script/*'
