packages:
  - 'client/*'
  - 'core/*'
  - '!core/tests'
  - 'core/config-editor/src-node-sidecar'
  - 'core/relay-server/client'
  - 'examples/full-local/game/*'
  - 'examples/full-local/integration'
  - 'examples/full-local/services/*'
  - 'plugins/download/archive/*'
  - 'plugins/download/compression/*'
  - 'plugins/download/protocol'
  - 'plugins/download/protocol/*'
  - 'plugins/download/shared'
  - 'plugins/untrusted/config/*'
  - 'plugins/untrusted/script/*'
  - 'tests/integration'
