// Bakes package.json's version into a source file at build time, so the
// version is embedded directly in the compiled/bundled output instead of
// being read from package.json at runtime (which wouldn't be available if
// this package is later packaged into a standalone binary, e.g. via pkg).
const { writeFileSync, mkdirSync } = require("node:fs");
const { join } = require("node:path");

const pkg = require("../package.json");

mkdirSync(join(__dirname, "..", "src"), { recursive: true });
writeFileSync(
  join(__dirname, "..", "src", "version.ts"),
  `// Generated by scripts/generate-version.js — do not edit by hand.\nexport const VERSION = ${JSON.stringify(pkg.version)};\n`
);
